TODO items annotated with referencing issue number
rgb-org/rgb-node pull request #167
Opened 2021-03-23 06:47 UTC by rajarshimaitra

2021-03-26 15:42 UTC, rajarshimaitra commented
Updated after removing Issue duplication and modified annotation.

2021-03-30 08:39 UTC, dr-orlovsky requested changes
One of TODOs was broken by `fmt` thing

2021-03-30 08:39 UTC, dr-orlovsky commented on src/fungibled/runtime.rs
>              // the same for Consignment
```suggestion
            // TODO #156: Improve RGB Core disclosure API providing methods for
            //      indexing underlying data in different ways. Do
            //      the same for Consignment
```

2021-03-30 12:05 UTC, rajarshimaitra commented
Updated..

2021-04-11 13:55 UTC, dr-orlovsky requested changes

2021-04-11 13:55 UTC, dr-orlovsky commented on src/error.rs
> +// (LNP/BP)
```suggestion
// TODO #152: Consider moving parts of this file to common daemon modules
//       (Internet2)
```

2021-04-11 13:55 UTC, dr-orlovsky commented on src/fungibled/runtime.rs
> +        // amount of asset for the transfer operation
```suggestion
        // TODO #66: Check inputs that they really exist and have sufficient
        //       amount of asset for the transfer operation
```

2021-04-11 13:55 UTC, dr-orlovsky commented on src/fungibled/runtime.rs
> +            // Consignment
```suggestion
            // TODO #156: Improve RGB Core disclosure API providing methods for
            //       indexing underlying data in different ways. Do the same for
            //       Consignment
```

2021-04-11 13:55 UTC, dr-orlovsky commented on src/i9n/runtime.rs
> +                // mode; remove them
```suggestion
                // TODO #159: Endpoint parameters are not needed in embedded
                //       mode; remove them
```

2021-04-11 13:55 UTC, dr-orlovsky commented on src/rpc/reply.rs
> +        // implementation of `ToValue` trait and derive macro for enums
```suggestion
        // TODO #61: Save error code taken from `Error::to_value()` after
        //       implementation of `ToValue` trait and derive macro for enums
```

2021-04-11 13:55 UTC, dr-orlovsky commented on src/rpc/reply.rs
> +        // implementation of `ToValue` trait and derive macro for enums
```suggestion
        // TODO #61: Save error code taken from `Error::to_value()` after
        //       implementation of `ToValue` trait and derive macro for enums
```

2021-04-11 13:55 UTC, dr-orlovsky commented on src/rpc/reply.rs
> +        // implementation of `ToValue` trait and derive macro for enums
```suggestion
        // TODO #61: Save error code taken from `Error::to_value()` after
        //       implementation of `ToValue` trait and derive macro for enums
```

2021-04-11 13:55 UTC, dr-orlovsky commented on src/rpc/reply.rs
> +        // implementation of `ToValue` trait and derive macro for enums
```suggestion
        // TODO #61: Save error code taken from `Error::to_value()` after
        //       implementation of `ToValue` trait and derive macro for enums
```

2021-04-11 13:55 UTC, dr-orlovsky commented on src/stashd/index/btree.rs
> +    /// display
```suggestion
    /// TODO #164: Replace with DisplayFromStr once RGB node will fix node
    ///       display
```

2021-04-11 13:55 UTC, dr-orlovsky commented on src/stashd/runtime.rs
> +        // over their direct ancestor in the same manner
```suggestion
        // TODO #63: Implement stash prunning: filter all transitions containing
        //       revealed outpoints from the removal_list, and if they do
        //       not have any other _known_ outpoints, remove them — and iterate
        //       over their direct ancestor in the same manner
```

2021-04-11 13:56 UTC, dr-orlovsky approved these changes

2021-04-11 13:57 UTC, dr-orlovsky approved these changes

2021-04-11 13:59 UTC, merged