Fix README instructions using cargo install and all-features for local source.
rgb-org/rgb-node pull request #172
Opened 2021-06-26 21:11 UTC by cryptoquick

The issue #170 intends to fix is valid, but I think a better approach was needed.

I made sure local source was used when installing. I think it's best we use install instead of pointing to the local target.

Also, I'm not 100% sure if we should also include a `--force` flag to the install command. If it's ever an issue in future releases, we might want that. Let me know if you'd like me to add it.

2021-08-01 14:14 UTC, dr-orlovsky requested changes
Why do you think it is a better alternative to https://github.com/rgb-org/rgb-node/pull/173?
 `~/.cargo` is a platform-dependend path and will fail on many machines.

My suggestion: leave line 129 fix and remove the rest of changes since they are already covered by just merged #173

2021-08-01 17:33 UTC, cryptoquick commented
That would only fail on machines running Windows, and even on Windows, most would use WSL. If there's somebody using Rust on Windows proper, maybe they can add Windows-specific instructions to the README.

I hadn't seen #173, I can merge main, but I think these are better instructions for most cases. I prefer using `cargo install` for user-facing stuff.

2021-11-13 10:50 UTC, dr-orlovsky approved these changes

2021-11-13 10:50 UTC, merged

2021-11-13 18:28 UTC, cryptoquick commented
Thanks!